import { GetStaticProps } from "next";
import Head from "next/head";
import Image from "next/image";
import heroImg from "../../public/assets/hero.png";
import styles from "@/styles/home.module.css";
import { collection, getDocs } from "firebase/firestore";
import { db } from "@/services/firebaseConnection";

interface HomeProps {
  posts: number;
  comments: number;
}

export default function Home({ posts, comments }: HomeProps) {
  return (
    <>
      <Head>
        <title>Tarefas+ | Organize suas tarefas de forma fácil</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>
          <div className={styles.logoContent}>
            <Image
              className={styles.hero}
              src={heroImg}
              alt="Logo tarefas"
              priority
            />
          </div>
          <h1 className={styles.title}>
            Sistema feito para <br />
            organizar seus estudo e tarefas
          </h1>
          <div className={styles.infoContent}>
            <section className={styles.box}>
              <span>+{comments} comentários</span>
            </section>
            <section className={styles.box}>
              <span>+{posts} posts</span>
            </section>
          </div>
        </main>
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const postsRef = collection(db, "Tasks");
  const commentsRef = collection(db, "comments");

  const commentSnapshot = await getDocs(commentsRef);
  const postSnapshot = await getDocs(postsRef);

  return {
    props: {
      posts: postSnapshot.size || 0,
      comments: commentSnapshot.size || 0,
    },
    revalidate: 60
  };
};
