import Head from "next/head";



export default function Home() {
  return (
    <div>
      <Head>
        <title>Tarefas+ | Organize suas tarefas de forma fácil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />        
      </Head>
      <h1>Meu app</h1>
    </div>
  );
}
