import Head from "next/head";
import Image from "next/image";
import heroImg from "../../public/assets/hero.png";
import styles from '@/styles/home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Tarefas+ | Organize suas tarefas de forma fácil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logoContent}>
          <Image
            className={styles.hero}
            src={heroImg}
            alt="Logo tarefas"
            priority
          />
        </div>
        <h1 className={styles.title}>
          Sistema feito para <br />
          organizar seus estudo e tarefas
        </h1>
        <div className={styles.infoContent}>
          <section className={styles.box}>
            <span>+90 comentários</span>            
          </section>
          <section className={styles.box}>
            <span>+30 posts</span>            
          </section>
        </div>
      </main>
    </>
  );
}
